language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache: yarn
jobs:
  include:
    - stage: deploy-preview-react
      before_install:
        - "node ./travis/deploy_preview.js $TRAVIS_PULL_REQUEST 'package: react'"
        - pip install awscli --user
        - aws configure set aws_access_key_id $COS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $COS_SECRET_ACCESS_KEY
      script:
        - yarn install
        - yarn build
        - cd packages/react
        - echo "SCROLL_TRACKING=true" >> .env
        - echo "CORS_PROXY=https://dds-proxy.mybluemix.net/" >> .env
        - yarn build-storybook --loglevel verbose
        - aws s3 cp storybook-static s3://ibmdotcom-react/deploy-previews/$TRAVIS_PULL_REQUEST --recursive --endpoint https://s3.us-south.cloud-object-storage.appdomain.cloud
    - stage: deploy-preview-expressive
      before_install:
          - "node ./travis/deploy_preview.js $TRAVIS_PULL_REQUEST 'package: styles'"
          - aws configure set aws_access_key_id $COS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $COS_SECRET_ACCESS_KEY
      script:
        - yarn install
        - yarn build
        - cd packages/styles
        - yarn build-storybook --loglevel verbose
        - aws s3 cp storybook-static s3://carbon-expressive/deploy-previews/$TRAVIS_PULL_REQUEST --recursive --endpoint https://s3.us-south.cloud-object-storage.appdomain.cloud
stages:
  - name: deploy-preview-react
    if: type = pull_request
  - name: deploy-preview-expressive
    if: type = pull_request
