language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - pip install awscli --user
  - aws configure set aws_access_key_id $COS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $COS_SECRET_ACCESS_KEY
cache: yarn
env:
  - PREVIEW_DOMAIN=s3.us-south.cloud-object-storage.appdomain.cloud
jobs:
  include:
    - stage: deploy-preview-react
      env:
        - $COS_BUCKET=ibmdotcom-react
      before_install:
        - aws --version
        - "node ./travis/deploy_preview.js $TRAVIS_PULL_REQUEST 'package: react'"
      script:
        - yarn install
        - yarn build
        - cd packages/react
        - echo "SCROLL_TRACKING=true" >> .env
        - echo "CORS_PROXY=https://dds-proxy.mybluemix.net/" >> .env
        - yarn build-storybook --loglevel verbose
        - aws s3 cp storybook-static s3://$COS_BUCKET/deploy-previews/$TRAVIS_PULL_REQUEST --recursive --endpoint https://$PREVIEW_DOMAIN
      after_success:
        - "curl -H 'Authorization: token $GITHUB_TOKEN' -X POST \
          -d {\"body\": \"Deploy preview created for package `Carbon Expressive`:
          https://$COS_BUCKET/deploy-previews/${PREVIEW_URL}/$TRAVIS_PULL_REQUEST/index.html

          Built with commit: [$TRAVIS_PULL_REQUEST_SHA](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_PULL_REQUEST_SHA})\"}" \
          "https://api.github.com/repos/$TRAVIS_REPO_SLUG/issues/$TRAVIS_PULL_REQUEST/comments"
    - stage: deploy-preview-expressive
      before_install:
          - aws --version
          - "node ./travis/deploy_preview.js $TRAVIS_PULL_REQUEST 'package: styles'"
      script:
        - yarn install
        - yarn build
        - cd packages/styles
        - yarn build-storybook --loglevel verbose
        - aws s3 cp storybook-static s3://carbon-expressive/deploy-previews/$TRAVIS_PULL_REQUEST --recursive --endpoint https://$PREVIEW_DOMAIN
      after_success:
        - "curl -H 'Authorization: token $GITHUB_TOKEN' -X POST
          -d {\"body\": \"Deploy preview created for package `Carbon Expressive`:
          https://$COS_BUCKET/deploy-previews/${PREVIEW_URL}/$TRAVIS_PULL_REQUEST/index.html

          Built with commit: [$TRAVIS_PULL_REQUEST_SHA](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_PULL_REQUEST_SHA})\"}
          https://api.github.com/repos/$TRAVIS_REPO_SLUG/issues/$TRAVIS_PULL_REQUEST/comments"
stages:
  - name: deploy-preview-react
    if: type = pull_request
  - name: deploy-preview-expressive
    if: type = pull_request
